/** @type {import('tailwindcss').Config} */
export default {
    content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "tertiary-container": "#005729",
                "on-secondary-container": "#4c5680",
                "error-container": "#ffdad6",
                "surface-container-high": "#dee9fc",
                "surface-container-low": "#eff4ff",
                "on-surface-variant": "#444653",
                "outline": "#757684",
                "on-primary-fixed": "#001453",
                "on-secondary": "#ffffff",
                "on-surface": "#121c2a",
                "primary-fixed-dim": "#b8c4ff",
                "background": "#f8f9ff",
                "error": "#ba1a1a",
                "surface-tint": "#3755c3",
                "inverse-on-surface": "#eaf1ff",
                "on-background": "#121c2a",
                "surface-dim": "#d0dbed",
                "primary": "#00288e",
                "surface-bright": "#f8f9ff",
                "inverse-surface": "#27313f",
                "on-error": "#ffffff",
                "surface": "#f8f9ff",
                "on-primary-container": "#a8b8ff",
                "surface-variant": "#d9e3f6",
                "on-tertiary-container": "#3ed478",
                "on-secondary-fixed": "#0e1840",
                "inverse-primary": "#b8c4ff",
                "surface-container-highest": "#d9e3f6",
                "primary-fixed": "#dde1ff",
                "tertiary": "#003d1b",
                "on-primary-fixed-variant": "#173bab",
                "primary-container": "#1e40af",
                "on-tertiary-fixed": "#00210c",
                "secondary-container": "#c3ccfe",
                "secondary": "#525c87",
                "on-error-container": "#93000a",
                "secondary-fixed-dim": "#bbc4f6",
                "outline-variant": "#c4c5d5",
                "on-primary": "#ffffff",
                "on-tertiary-fixed-variant": "#005227",
                "tertiary-fixed-dim": "#4de082",
                "secondary-fixed": "#dde1ff",
                "on-secondary-fixed-variant": "#3b446e",
                "on-tertiary": "#ffffff",
                "surface-container-lowest": "#ffffff",
                "tertiary-fixed": "#6dfe9c",
                "surface-container": "#e6eeff"
            },
            fontFamily: {
                "headline": ["Inter", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"],
                "sans": ["Inter", "sans-serif"]
            },
            borderRadius: {
                "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "2xl": "1rem", "3xl": "1.5rem", "full": "9999px"
            },
        },
    },
    plugins: [],
}
